"""Update CalendarEvent for Phase 12

Revision ID: 1bb96ddb3f9b
Revises: 578c36fc147b
Create Date: 2026-09-06 18:37:35.100942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb96ddb3f9b'
down_revision = '578c36fc147b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('school_class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school_year_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key('fk_calendar_events_school_years', 'school_years', ['school_year_id'], ['id'])
        batch_op.create_foreign_key('fk_calendar_events_school_classes', 'school_classes', ['school_class_id'], ['id'])
        batch_op.create_foreign_key('fk_calendar_events_subjects', 'subjects', ['subject_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_calendar_events_school_years', type_='foreignkey')
        batch_op.drop_constraint('fk_calendar_events_school_classes', type_='foreignkey')
        batch_op.drop_constraint('fk_calendar_events_subjects', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('school_year_id')
        batch_op.drop_column('subject_id')
        batch_op.drop_column('school_class_id')
        batch_op.drop_column('all_day')

    # ### end Alembic commands ###
