"""Implementa modulo academico de avaliacoes

Revision ID: c544d707b68d
Revises: 9de19204b3b2
Create Date: 2026-09-05 22:22:07.409241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c544d707b68d'
down_revision = '9de19204b3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('assessment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('assessment_type')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
